import { getLanguage } from "obsidian";

/**
 * Exported-page UI language. Requirement (REQUIREMENTS.md v1.1):
 * follow Obsidian's app language; support zh-TW / en / ja; anything else → en.
 */
export type NpLocale = "en" | "zh-TW" | "ja";

export type NpStringKey =
	| "generatedAt"
	| "sourceVault"
	| "sourceBase"
	| "rows"
	| "emptyCell"
	| "ungrouped"
	| "sourceNote"
	| "stubBanner"
	| "linkOutOfScope"
	| "brokenImage"
	| "viewTypeFallback"
	| "externalEmbed"
	| "searchPlaceholder"
	| "searchNoResults"
	| "home"
	| "menu"
	| "errorTitle"
	| "errorNoQueryData"
	| "footerLine"
	| "loginTitle"
	| "loginPasswordLabel"
	| "loginRemember"
	| "loginSubmit"
	| "loginWrong"
	| "settingsDiagName"
	| "settingsDiagDesc"
	| "settingsEntropyName"
	| "settingsEntropyDesc"
	| "settingsRememberName"
	| "settingsRememberDesc"
	| "settingsDevName"
	| "settingsDevDesc";

const STRINGS: Record<NpLocale, Record<NpStringKey, string>> = {
	en: {
		generatedAt: "Generated at",
		sourceVault: "Source vault",
		sourceBase: "Source base",
		rows: "{n} rows",
		emptyCell: "",
		ungrouped: "(No value)",
		sourceNote: "Source note",
		stubBanner:
			"Note content export arrives in a later step; the raw source is shown below for now.",
		linkOutOfScope: "Not in this export",
		brokenImage: "image not found",
		viewTypeFallback:
			'View type "{type}" is not supported yet — shown as a table for now.',
		externalEmbed: "External content",
		searchPlaceholder: "Search…",
		searchNoResults: "No results",
		home: "HOME",
		menu: "Menu",
		errorTitle: "Export problem",
		errorNoQueryData:
			"Timed out waiting for Obsidian to provide the Bases query result. Nothing was exported for this base.",
		footerLine: "Generated by VaultPack",
		loginTitle: "Password required",
		loginPasswordLabel: "Password",
		loginRemember: "Remember on this device",
		loginSubmit: "Open",
		loginWrong: "Wrong password. Please try again.",
		settingsDiagName: "Include diagnostics in web packages",
		settingsDiagDesc:
			"Ship url-map / export-report and other developer diagnostics inside Public / Link-only / Password packages. Off by default (diagnostics leak note paths and internal structure); when enabled, the .htaccess still blocks direct web access. Local folder and encrypted ZIP exports always include diagnostics regardless.",
		settingsEntropyName: "High-entropy folder names (Link-only / Password)",
		settingsEntropyDesc:
			"Name export folders vaultpack-s-XXXX… / vaultpack-p-XXXX… (unguessable URLs). When off, timestamp names are used — Link-only protection becomes much weaker. Keeping this on is recommended.",
		settingsRememberName: "Password mode: “remember me” duration (days)",
		settingsRememberDesc:
			"How long a device stays signed in after checking “Remember on this device” (1–365, default 30). Without it, closing the browser signs out.",
		settingsDevName: "Developer mode",
		settingsDevDesc:
			"Show developer commands (test page, Bases probe, five-mode test export). Takes effect after the plugin reloads.",
	},
	"zh-TW": {
		generatedAt: "產生時間",
		sourceVault: "來源 vault",
		sourceBase: "來源 Base",
		rows: "共 {n} 列",
		emptyCell: "",
		ungrouped: "（未分組）",
		sourceNote: "來源筆記",
		stubBanner: "筆記內文匯出將在後續階段完成；以下先顯示原始內容。",
		linkOutOfScope: "不在此匯出包內",
		brokenImage: "找不到圖片",
		viewTypeFallback: "「{type}」類型視圖尚未支援，先以表格呈現。",
		externalEmbed: "外部內容",
		searchPlaceholder: "搜尋…",
		searchNoResults: "沒有結果",
		home: "首頁",
		menu: "選單",
		errorTitle: "匯出問題",
		errorNoQueryData:
			"等不到 Obsidian 提供 Bases 查詢結果（逾時）。這個 Base 沒有匯出任何內容。",
		footerLine: "由 VaultPack 產生",
		loginTitle: "需要密碼",
		loginPasswordLabel: "密碼",
		loginRemember: "在這台裝置上記住我",
		loginSubmit: "開啟",
		loginWrong: "密碼錯誤，請再試一次。",
		settingsDiagName: "Web 包附診斷檔",
		settingsDiagDesc:
			"把 url-map／export-report 等開發診斷檔一併放進 Public／僅限連結／密碼保護包。預設關閉（診斷檔會洩漏筆記路徑等內部結構）；開啟時 .htaccess 仍會擋外部直接讀取。本機資料夾與加密 ZIP 一律附診斷檔，不受此設定影響。",
		settingsEntropyName: "高亂度資料夾名（僅限連結／密碼模式）",
		settingsEntropyDesc:
			"匯出資料夾命名為 vaultpack-s-XXXX…／vaultpack-p-XXXX…（無法被猜到的網址）。關閉後改用時間戳命名——「僅限連結」模式的保護大幅減弱，不建議關閉。",
		settingsRememberName: "密碼模式「記住我」天數",
		settingsRememberDesc:
			"登入頁勾選「記住我」後，這台裝置維持登入的天數（1–365，預設 30）。不勾選時關閉瀏覽器即登出。",
		settingsDevName: "開發者模式",
		settingsDevDesc:
			"顯示開發用指令（測試頁、Bases 探測、五模式測試匯出）。外掛重新載入後生效。",
	},
	ja: {
		generatedAt: "生成時刻",
		sourceVault: "元の vault",
		sourceBase: "元の Base",
		rows: "全 {n} 行",
		emptyCell: "",
		ungrouped: "（グループなし）",
		sourceNote: "元のノート",
		stubBanner: "ノート本文の書き出しは後続ステップで対応予定。以下は元テキストです。",
		linkOutOfScope: "このエクスポートには含まれていません",
		brokenImage: "画像が見つかりません",
		viewTypeFallback: "「{type}」タイプのビューは未対応のため、表として表示しています。",
		externalEmbed: "外部コンテンツ",
		searchPlaceholder: "検索…",
		searchNoResults: "結果なし",
		home: "ホーム",
		menu: "メニュー",
		errorTitle: "エクスポートの問題",
		errorNoQueryData:
			"Obsidian から Bases のクエリ結果を取得できませんでした（タイムアウト）。この Base は何もエクスポートされていません。",
		footerLine: "VaultPack により生成",
		loginTitle: "パスワードが必要です",
		loginPasswordLabel: "パスワード",
		loginRemember: "このデバイスでは記憶する",
		loginSubmit: "開く",
		loginWrong: "パスワードが違います。もう一度お試しください。",
		settingsDiagName: "Web パッケージに診断ファイルを含める",
		settingsDiagDesc:
			"url-map／export-report などの開発用診断ファイルを Public／リンク限定／パスワード保護パッケージに同梱します。既定はオフ（診断ファイルはノートのパスなど内部構造を漏らします）。オンの場合も .htaccess が外部からの直接読み取りをブロックします。ローカルフォルダと暗号化 ZIP には常に同梱されます。",
		settingsEntropyName: "高エントロピーなフォルダ名（リンク限定／パスワード）",
		settingsEntropyDesc:
			"エクスポートフォルダを vaultpack-s-XXXX…／vaultpack-p-XXXX…（推測不可能な URL）と命名します。オフにするとタイムスタンプ名になり、リンク限定モードの保護は大幅に弱まります。オンのままを推奨します。",
		settingsRememberName: "パスワードモード「記憶する」日数",
		settingsRememberDesc:
			"ログインページで「このデバイスでは記憶する」を選んだ後、ログイン状態を保つ日数（1–365、既定 30）。選ばない場合はブラウザを閉じるとログアウトします。",
		settingsDevName: "開発者モード",
		settingsDevDesc:
			"開発用コマンド（テストページ、Bases プローブ、5 モードテストエクスポート）を表示します。プラグインの再読み込み後に有効になります。",
	},
};

/** zh-TW exact; ja by prefix; everything else falls back to en. */
export function resolveLocale(): NpLocale {
	const lang = typeof getLanguage === "function" ? getLanguage() : "en";
	if (lang === "zh-TW") {
		return "zh-TW";
	}
	if (lang === "ja" || lang.startsWith("ja-")) {
		return "ja";
	}
	return "en";
}

export function t(
	locale: NpLocale,
	key: NpStringKey,
	vars?: Record<string, string | number>,
): string {
	let s = STRINGS[locale][key];
	if (vars) {
		for (const [k, v] of Object.entries(vars)) {
			s = s.replace(`{${k}}`, String(v));
		}
	}
	return s;
}
