import bcrypt from "bcryptjs";
import { NpLocale, t } from "./i18n";
import { GATE_PAGE_CSS, TOKENS_CSS } from "./design-tokens";

/**
 * Password-protected web mode (spec §5): a generated PHP gate for plain
 * Apache/PHP shared hosting. The plugin generates the bcrypt hash locally
 * (spec §5.4 "generate an equivalent hash in the plugin") — the plaintext
 * password never reaches any output file. PHP syntax targets 7.0+ with
 * guarded 7.3+ cookie options (typical WordPress-grade hosts).
 */
export interface PhpGateFiles {
	indexPhp: string;
	logoutPhp: string;
	/** probe file placed INSIDE the private dir; must be unreachable directly */
	probeName: string;
	probeContent: string;
}

/** bcrypt via bcryptjs ($2b$). PHP password_verify() accepts $2a/$2b/$2y —
 * verified live against the local php CLI during this batch's self-test. */
export function hashPassword(password: string): string {
	const hash = bcrypt.hashSync(password, 10);
	if (!/^\$2[aby]\$/.test(hash)) {
		throw new Error(`bcrypt 產出格式異常（loud fail）：${hash.slice(0, 6)}…`);
	}
	return hash;
}

export function buildPhpGate(opts: {
	privateSubdir: string;
	passwordHash: string;
	locale: NpLocale;
	version: string;
	/** "remember on this device" lifetime in days (settings, default 30) */
	rememberDays?: number;
}): PhpGateFiles {
	const { privateSubdir, passwordHash, locale, version } = opts;
	const rememberDays = Math.min(
		365,
		Math.max(1, Math.round(opts.rememberDays ?? 30)),
	);
	if (passwordHash.includes("'")) {
		throw new Error("hash 含單引號，拒絕生成（loud fail）");
	}
	const L = {
		title: t(locale, "loginTitle"),
		password: t(locale, "loginPasswordLabel"),
		remember: t(locale, "loginRemember"),
		submit: t(locale, "loginSubmit"),
		wrong: t(locale, "loginWrong"),
	};
	const esc = (s: string) =>
		s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
	// The token CSS carries apostrophes in its comments (e.g. "topbar's");
	// it is emitted inside a PHP single-quoted string, so backslashes and
	// single quotes must be escaped for that context or the generated PHP
	// breaks (2026-07-05: index.php line ~218 parse error).
	const phpSq = (s: string) => s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
	const gateStyleCss = phpSq(TOKENS_CSS + GATE_PAGE_CSS);

	const indexPhp = `<?php
// VaultPack password gate — generated by VaultPack v${version}. Do not edit.
// Serves files from the private package folder to authenticated sessions only.

$np_private = '${privateSubdir}';
$np_hash = '${passwordHash}';
$np_remember_days = ${rememberDays};

header('X-VaultPack-Gate: 1');
header('X-Robots-Tag: noindex, nofollow, noarchive, nosnippet, noimageindex');
header('Referrer-Policy: no-referrer');
header('X-Content-Type-Options: nosniff');

$np_secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
	|| (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https');
// Base URL of the package. Derived from __DIR__ vs DOCUMENT_ROOT — stable per
// package. dirname(SCRIPT_NAME) is NOT usable: php -S router mode sets
// SCRIPT_NAME to the REQUEST path, which made the session cookie path drift
// (caught by the 2026-07-04 self-test battery).
$np_base = np_base_path();
session_name('NPSESS');
np_cookie_params($np_base, $np_secure);
session_start();

// Apache rewrite passes ?np_path=…; without it (php -S router mode, or a
// host that lost the rewrite), derive the path from REQUEST_URI instead.
$np_path = isset($_GET['np_path']) ? (string)$_GET['np_path'] : null;
if ($np_path === null) {
	$uri = (string)parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
	if (strpos($uri, $np_base) === 0) {
		$np_path = rawurldecode(substr($uri, strlen($np_base)));
	} else {
		$np_path = '';
	}
}
if ($np_path === 'index.php') { $np_path = ''; }
$np_login_error = false;

// logout works both as the standalone logout.php (Apache passes it through)
// and through the gate (php -S router mode routes everything here).
if ($np_path === 'logout.php') {
	$_SESSION = array();
	if (ini_get('session.use_cookies')) {
		setcookie(session_name(), '', time() - 42000, $np_base, '', $np_secure, true);
	}
	session_destroy();
	header('Location: ' . $np_base);
	exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['np_password'])) {
	if (password_verify((string)$_POST['np_password'], $np_hash)) {
		session_regenerate_id(true);
		$_SESSION['np_auth'] = true;
		if (!empty($_POST['np_remember'])) {
			np_set_cookie(session_name(), session_id(), time() + 86400 * $np_remember_days, $np_base, $np_secure);
		}
		$dest = isset($_POST['np_dest']) ? (string)$_POST['np_dest'] : '';
		if (!np_path_ok($dest) || strpos($dest, 'np-selfcheck') === 0) { $dest = ''; }
		header('Location: ' . $np_base . $dest);
		exit;
	}
	$np_login_error = true;
}

if ($np_path === 'np-selfcheck') { np_selfcheck_page($np_private, $np_base); exit; }

if (!isset($_SESSION['np_auth']) || $_SESSION['np_auth'] !== true) {
	np_login_page($np_path, $np_login_error, $np_base);
	exit;
}

np_serve($np_private, $np_path);
exit;

function np_base_path() {
	$doc = isset($_SERVER['DOCUMENT_ROOT'])
		? rtrim(str_replace('\\\\', '/', (string)$_SERVER['DOCUMENT_ROOT']), '/')
		: '';
	$dir = str_replace('\\\\', '/', __DIR__);
	if ($doc !== '' && strpos($dir, $doc) === 0) {
		$rel = trim(substr($dir, strlen($doc)), '/');
		return $rel === '' ? '/' : '/' . $rel . '/';
	}
	$d = str_replace('\\\\', '/', dirname((string)$_SERVER['SCRIPT_NAME']));
	return rtrim($d, '/') . '/';
}

function np_cookie_params($base, $secure) {
	if (PHP_VERSION_ID >= 70300) {
		session_set_cookie_params(array(
			'lifetime' => 0, 'path' => $base, 'secure' => $secure,
			'httponly' => true, 'samesite' => 'Lax',
		));
	} else {
		session_set_cookie_params(0, $base, '', $secure, true);
	}
}

function np_set_cookie($name, $value, $expires, $base, $secure) {
	if (PHP_VERSION_ID >= 70300) {
		setcookie($name, $value, array(
			'expires' => $expires, 'path' => $base, 'secure' => $secure,
			'httponly' => true, 'samesite' => 'Lax',
		));
	} else {
		setcookie($name, $value, $expires, $base, '', $secure, true);
	}
}

// Path safety (spec §5.4): no null bytes, no absolute paths, no dot-dot.
function np_path_ok($p) {
	if ($p === '') { return true; }
	if (strpos($p, "\\0") !== false) { return false; }
	$c = substr($p, 0, 1);
	if ($c === '/' || $c === '\\\\') { return false; }
	if (preg_match('#^[A-Za-z]:#', $p)) { return false; }
	if (preg_match('#(^|[\\\\\\\\/])\\.\\.($|[\\\\\\\\/])#', $p)) { return false; }
	return true;
}

function np_serve($privateDir, $path) {
	$path = str_replace('\\\\', '/', $path);
	if ($path === '') { $path = 'START_HERE.html'; }
	if (!np_path_ok($path)) { np_404(); }
	// direct requests INTO the private tree 404 even when authenticated —
	// parity with the Apache RewriteRule ^_np_private_ [R=404].
	if (strpos($path, '_np_private_') === 0) { np_404(); }
	$name = basename($path);
	if (strncasecmp($name, '.ht', 3) === 0) { np_404(); }
	$root = realpath(__DIR__ . '/' . $privateDir);
	if ($root === false) { np_500('private folder missing'); }
	$full = realpath($root . '/' . $path);
	if ($full === false || strncmp($full, $root . DIRECTORY_SEPARATOR, strlen($root) + 1) !== 0 || is_dir($full)) {
		np_404();
	}
	$types = array(
		'html' => 'text/html; charset=utf-8',
		'css' => 'text/css; charset=utf-8',
		'js' => 'text/javascript; charset=utf-8',
		'mjs' => 'text/javascript; charset=utf-8',
		'json' => 'application/json; charset=utf-8',
		'svg' => 'image/svg+xml',
		'png' => 'image/png', 'jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg',
		'gif' => 'image/gif', 'webp' => 'image/webp', 'avif' => 'image/avif',
		'bmp' => 'image/bmp', 'ico' => 'image/x-icon',
		'pdf' => 'application/pdf',
		'txt' => 'text/plain; charset=utf-8',
		'xml' => 'application/xml; charset=utf-8',
		'woff' => 'font/woff', 'woff2' => 'font/woff2',
		'ttf' => 'font/ttf', 'otf' => 'font/otf',
		'mp4' => 'video/mp4', 'webm' => 'video/webm',
		'mp3' => 'audio/mpeg', 'm4a' => 'audio/mp4',
		'wav' => 'audio/wav', 'ogg' => 'audio/ogg',
		'zip' => 'application/zip',
	);
	$dot = strrpos($name, '.');
	$ext = $dot === false ? '' : strtolower(substr($name, $dot + 1));
	header('Content-Type: ' . (isset($types[$ext]) ? $types[$ext] : 'application/octet-stream'));
	header('Content-Length: ' . (string)filesize($full));
	readfile($full);
	exit;
}

function np_404() {
	http_response_code(404);
	header('Content-Type: text/plain; charset=utf-8');
	echo 'Not found';
	exit;
}

function np_500($msg) {
	http_response_code(500);
	header('Content-Type: text/plain; charset=utf-8');
	echo 'VaultPack gate error: ' . $msg;
	exit;
}

function np_page_top($title) {
	header('Content-Type: text/html; charset=utf-8');
	// design-token template (design-tokens.ts is the single source; raw
	// values are forbidden here — REQUIREMENTS scope fix 2026-07-04)
	echo '<!DOCTYPE html><html><head><meta charset="utf-8">'
		. '<meta name="viewport" content="width=device-width, initial-scale=1">'
		. '<meta name="robots" content="noindex,nofollow,noarchive,nosnippet,noimageindex">'
		. '<meta name="referrer" content="no-referrer">'
		. '<title>' . htmlspecialchars($title, ENT_QUOTES) . '</title>'
		. '<style>${gateStyleCss}</style>'
		. '</head><body class="np-gate"><div class="np-card">';
}

function np_page_bottom() {
	echo '</div></body></html>';
	exit;
}

function np_login_page($dest, $error, $base) {
	np_page_top('${esc(L.title)}');
	echo '<h1>${esc(L.title)}</h1>';
	if ($error) { echo '<p class="np-err">${esc(L.wrong)}</p>'; }
	echo '<form method="post" action="' . htmlspecialchars($base, ENT_QUOTES) . '">'
		. '<label>${esc(L.password)}</label>'
		. '<input type="password" name="np_password" autofocus autocomplete="current-password">'
		. '<input type="hidden" name="np_dest" value="' . htmlspecialchars($dest, ENT_QUOTES) . '">'
		. '<label class="np-remember"><input type="checkbox" name="np_remember" value="1"> ${esc(L.remember)}</label>'
		. '<button type="submit">${esc(L.submit)}</button>'
		. '</form>'
		. '<div class="np-foot"><a href="' . htmlspecialchars($base, ENT_QUOTES) . '?np_path=np-selfcheck">self-check</a>'
		. ' · VaultPack v${version}</div>';
	np_page_bottom();
}

// Spec §5.6: verify the host actually protects the private folder.
// Server-side facts + client-side probes (rewrite + direct private access).
function np_selfcheck_page($privateDir, $base) {
	$root = realpath(__DIR__ . '/' . $privateDir);
	$sessionOk = session_status() === PHP_SESSION_ACTIVE;
	np_page_top('VaultPack self-check');
	echo '<h1>VaultPack self-check</h1><ul>'
		. '<li>PHP: <span class="np-ok">running (' . htmlspecialchars(PHP_VERSION, ENT_QUOTES) . ')</span></li>'
		. '<li>Sessions: ' . ($sessionOk ? '<span class="np-ok">active</span>' : '<span class="np-bad">NOT working</span>') . '</li>'
		. '<li>Private folder on server: ' . ($root !== false ? '<span class="np-ok">found</span>' : '<span class="np-bad">MISSING</span>') . '</li>'
		. '<li>Rewrite (.htaccess): <span id="np-rw">checking…</span></li>'
		. '<li>Private folder blocked from direct access: <span id="np-priv">checking…</span></li>'
		. '</ul>'
		. '<p id="np-verdict"></p>'
		. '<div class="np-foot"><a href="' . htmlspecialchars($base, ENT_QUOTES) . '">back</a></div>';
	echo '<script>'
		. 'var base=' . json_encode($base) . ',priv=' . json_encode($privateDir) . ';'
		. 'function mark(id,ok,txt){var el=document.getElementById(id);'
		. 'el.textContent=txt;el.className=ok?"np-ok":"np-bad";}'
		. 'function verdict(){var bad=document.querySelectorAll(".np-bad").length;'
		. 'var v=document.getElementById("np-verdict");'
		. 'if(bad>0){v.className="np-bad";v.textContent="Security check failed: your web host is serving private package files directly. Do not use this upload for password-protected sharing.";}'
		. 'else{v.className="np-ok";v.textContent="All checks passed.";}}'
		. 'fetch(base+"np-rewrite-probe",{credentials:"omit"}).then(function(r){'
		. 'mark("np-rw",r.headers.get("X-VaultPack-Gate")==="1","gate header seen: rewrite works");'
		. '}).catch(function(){mark("np-rw",false,"probe failed");}).then(function(){'
		. 'return fetch(base+priv+"/np-probe.txt",{credentials:"omit"});'
		. '}).then(function(r){'
		. 'if(r&&r.status===200&&r.headers.get("X-VaultPack-Gate")!=="1"){mark("np-priv",false,"EXPOSED (direct read succeeded)");}'
		. 'else{mark("np-priv",true,"blocked");}'
		. '}).catch(function(){mark("np-priv",true,"blocked (request failed)");})'
		. '.then(verdict,verdict);'
		. '</script>';
	np_page_bottom();
}
`;

	const logoutPhp = `<?php
// VaultPack password gate — logout. Generated by VaultPack v${version}.
header('X-VaultPack-Gate: 1');
header('X-Robots-Tag: noindex, nofollow, noarchive, nosnippet, noimageindex');
$np_secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
	|| (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https');
$np_doc = isset($_SERVER['DOCUMENT_ROOT'])
	? rtrim(str_replace('\\\\', '/', (string)$_SERVER['DOCUMENT_ROOT']), '/')
	: '';
$np_dir = str_replace('\\\\', '/', __DIR__);
if ($np_doc !== '' && strpos($np_dir, $np_doc) === 0) {
	$np_rel = trim(substr($np_dir, strlen($np_doc)), '/');
	$np_base = $np_rel === '' ? '/' : '/' . $np_rel . '/';
} else {
	$np_base = rtrim(str_replace('\\\\', '/', dirname((string)$_SERVER['SCRIPT_NAME'])), '/') . '/';
}
session_name('NPSESS');
if (PHP_VERSION_ID >= 70300) {
	session_set_cookie_params(array('lifetime' => 0, 'path' => $np_base, 'secure' => $np_secure, 'httponly' => true, 'samesite' => 'Lax'));
} else {
	session_set_cookie_params(0, $np_base, '', $np_secure, true);
}
session_start();
$_SESSION = array();
if (ini_get('session.use_cookies')) {
	setcookie(session_name(), '', time() - 42000, $np_base, '', $np_secure, true);
}
session_destroy();
header('Location: ' . $np_base);
exit;
`;

	return {
		indexPhp,
		logoutPhp,
		probeName: "np-probe.txt",
		probeContent:
			"VaultPack private-folder probe. If you can read this over the web, the host is NOT protecting the private folder.\n",
	};
}
